services:
  - type: web
    name: gombonmongoli-chatbot
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production